<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/09/22 16:10:19
sfConfig::add(array(
  'app_sf_guard_plugin_remember_key_expiration_age' => 2592000,
  'app_sf_guard_plugin_remember_cookie_name' => 'myAppRememberMe',
  'app_doctrine_class' => 'sfDoctrineDatabase',
  'app_doctrine_param' => array (
  'dsn' => 'mysql:host=localhost;dbname=mydbname',
  'username' => 'user',
  'password' => 'password',
  'attributes' => 
  array (
    'default_table_collate' => 'utf8_general_ci',
    'default_table_charset' => 'utf8',
  ),
),
));
