generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Point
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          point
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [ id, name, placed_date, longitude, latitude, altitude, local_name, line ]
      filter:
        display: [ name, line ]
      form:    ~
      edit:    ~
      new:     ~
