<?php

/**
 * BasePointStat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $uid
 * @property string $l
 * @property string $p
 * @property integer $m
 * @property integer $page
 * 
 * @method integer   getUid()  Returns the current record's "uid" value
 * @method string    getL()    Returns the current record's "l" value
 * @method string    getP()    Returns the current record's "p" value
 * @method integer   getM()    Returns the current record's "m" value
 * @method integer   getPage() Returns the current record's "page" value
 * @method PointStat setUid()  Sets the current record's "uid" value
 * @method PointStat setL()    Sets the current record's "l" value
 * @method PointStat setP()    Sets the current record's "p" value
 * @method PointStat setM()    Sets the current record's "m" value
 * @method PointStat setPage() Sets the current record's "page" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     SKiPP
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePointStat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('point_stat');
        $this->hasColumn('uid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('l', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('p', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('m', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('page', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}