all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=junaio'
      username: root
      password: sk11pp
    attributes:
      default_table_collate: utf8_general_ci
      default_table_charset: utf8