<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/09/22 16:35:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=junaio',
  'username' => 'root',
  'password' => 'sk11pp',
  'name' => 'doctrine',
)),);
